package com.example.mydemo.dao;

import com.example.mydemo.bean.Herodictionary;
import org.apache.ibatis.annotations.Select;
import org.springframework.stereotype.Repository;

import java.util.Set;

@Repository
public interface HerodictionaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table herodictionary
     *
     * @mbg.generated
     */
    int insert(Herodictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table herodictionary
     *
     * @mbg.generated
     */
    int insertSelective(Herodictionary record);

    @Select("SELECT `mod`,GROUP_CONCAT(`name` SEPARATOR '|'),GROUP_CONCAT(`dictvalue` SEPARATOR '|') FROM herodictionary" +
            "    where usestatus = #{usestatus,jdbcType=BIT} " +
            "    GROUP BY `mod`\n" +
            "    ORDER BY `mod` DESC;")
    Set<Herodictionary> queryAll(Integer usestatus);

    /*@Select("SELECT * FROM herodictionary" +
            "    where usestatus = #{usestatus,jdbcType=BIT} " +
            "    and  `mod` = #{mod,jdbcType=VARCHAR}")
    Set<Herodictionary> queryByMod(Integer usestatus,String mod);*/

    @Select("SELECT * FROM herodictionary" +
            "    where usestatus = 0 " +
            "    and  `mod` = #{mod,jdbcType=VARCHAR}")
    Set<Herodictionary> queryByModUse(String mod);
}