package com.example.mydemo.dao;

import com.example.mydemo.bean.Jineng;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Options;
import org.springframework.stereotype.Repository;

@Repository
public interface JinengMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jineng
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jineng
     *
     * @mbg.generated
     */
    @Insert("insert into jineng (id, name, level, \n" +
            "      zhongzu, shuxing, hp, \n" +
            "      mp, gjl, jueduigjl, fyl, \n" +
            "      jueduifyl, maxhp, maxmp, \n" +
            "      maxgjl, maxjueduigjl, maxfyl, \n" +
            "      maxjueduifyl, xiaoguoleixing, leixing, \n" +
            "      needhp, needmp, needleixing\n" +
            "      )\n" +
            "    values (#{id,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, #{level,jdbcType=INTEGER}, \n" +
            "      #{zhongzu,jdbcType=INTEGER}, #{shuxing,jdbcType=INTEGER}, #{hp,jdbcType=BIGINT}, \n" +
            "      #{mp,jdbcType=BIGINT}, #{gjl,jdbcType=BIGINT}, #{jueduigjl,jdbcType=BIGINT}, #{fyl,jdbcType=BIGINT}, \n" +
            "      #{jueduifyl,jdbcType=BIGINT}, #{maxhp,jdbcType=BIGINT}, #{maxmp,jdbcType=BIGINT}, \n" +
            "      #{maxgjl,jdbcType=BIGINT}, #{maxjueduigjl,jdbcType=BIGINT}, #{maxfyl,jdbcType=BIGINT}, \n" +
            "      #{maxjueduifyl,jdbcType=BIGINT}, #{xiaoguoleixing,jdbcType=INTEGER}, #{leixing,jdbcType=INTEGER}, \n" +
            "      #{needhp,jdbcType=BIGINT}, #{needmp,jdbcType=BIGINT}, #{needleixing,jdbcType=INTEGER}\n" +
            "      )")
    @Options(useGeneratedKeys = true,keyProperty = "id",keyColumn = "id")
    int insert(Jineng record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jineng
     *
     * @mbg.generated
     */
    @Insert("<script>insert into jineng\n" +
            "    <trim prefix=\"(\" suffix=\")\" suffixOverrides=\",\">\n" +
            "      <if test=\"id != null\">\n" +
            "        id,\n" +
            "      </if>\n" +
            "      <if test=\"name != null\">\n" +
            "        name,\n" +
            "      </if>\n" +
            "      <if test=\"level != null\">\n" +
            "        level,\n" +
            "      </if>\n" +
            "      <if test=\"zhongzu != null\">\n" +
            "        zhongzu,\n" +
            "      </if>\n" +
            "      <if test=\"shuxing != null\">\n" +
            "        shuxing,\n" +
            "      </if>\n" +
            "      <if test=\"hp != null\">\n" +
            "        hp,\n" +
            "      </if>\n" +
            "      <if test=\"mp != null\">\n" +
            "        mp,\n" +
            "      </if>\n" +
            "      <if test=\"gjl != null\">\n" +
            "        gjl,\n" +
            "      </if>\n" +
            "      <if test=\"jueduigjl != null\">\n" +
            "        jueduigjl,\n" +
            "      </if>\n" +
            "      <if test=\"fyl != null\">\n" +
            "        fyl,\n" +
            "      </if>\n" +
            "      <if test=\"jueduifyl != null\">\n" +
            "        jueduifyl,\n" +
            "      </if>\n" +
            "      <if test=\"maxhp != null\">\n" +
            "        maxhp,\n" +
            "      </if>\n" +
            "      <if test=\"maxmp != null\">\n" +
            "        maxmp,\n" +
            "      </if>\n" +
            "      <if test=\"maxgjl != null\">\n" +
            "        maxgjl,\n" +
            "      </if>\n" +
            "      <if test=\"maxjueduigjl != null\">\n" +
            "        maxjueduigjl,\n" +
            "      </if>\n" +
            "      <if test=\"maxfyl != null\">\n" +
            "        maxfyl,\n" +
            "      </if>\n" +
            "      <if test=\"maxjueduifyl != null\">\n" +
            "        maxjueduifyl,\n" +
            "      </if>\n" +
            "      <if test=\"xiaoguoleixing != null\">\n" +
            "        xiaoguoleixing,\n" +
            "      </if>\n" +
            "      <if test=\"leixing != null\">\n" +
            "        leixing,\n" +
            "      </if>\n" +
            "      <if test=\"needhp != null\">\n" +
            "        needhp,\n" +
            "      </if>\n" +
            "      <if test=\"needmp != null\">\n" +
            "        needmp,\n" +
            "      </if>\n" +
            "      <if test=\"needleixing != null\">\n" +
            "        needleixing,\n" +
            "      </if>\n" +
            "    </trim>\n" +
            "    <trim prefix=\"values (\" suffix=\")\" suffixOverrides=\",\">\n" +
            "      <if test=\"id != null\">\n" +
            "        #{id,jdbcType=INTEGER},\n" +
            "      </if>\n" +
            "      <if test=\"name != null\">\n" +
            "        #{name,jdbcType=VARCHAR},\n" +
            "      </if>\n" +
            "      <if test=\"level != null\">\n" +
            "        #{level,jdbcType=INTEGER},\n" +
            "      </if>\n" +
            "      <if test=\"zhongzu != null\">\n" +
            "        #{zhongzu,jdbcType=INTEGER},\n" +
            "      </if>\n" +
            "      <if test=\"shuxing != null\">\n" +
            "        #{shuxing,jdbcType=INTEGER},\n" +
            "      </if>\n" +
            "      <if test=\"hp != null\">\n" +
            "        #{hp,jdbcType=BIGINT},\n" +
            "      </if>\n" +
            "      <if test=\"mp != null\">\n" +
            "        #{mp,jdbcType=BIGINT},\n" +
            "      </if>\n" +
            "      <if test=\"gjl != null\">\n" +
            "        #{gjl,jdbcType=BIGINT},\n" +
            "      </if>\n" +
            "      <if test=\"jueduigjl != null\">\n" +
            "        #{jueduigjl,jdbcType=BIGINT},\n" +
            "      </if>\n" +
            "      <if test=\"fyl != null\">\n" +
            "        #{fyl,jdbcType=BIGINT},\n" +
            "      </if>\n" +
            "      <if test=\"jueduifyl != null\">\n" +
            "        #{jueduifyl,jdbcType=BIGINT},\n" +
            "      </if>\n" +
            "      <if test=\"maxhp != null\">\n" +
            "        #{maxhp,jdbcType=BIGINT},\n" +
            "      </if>\n" +
            "      <if test=\"maxmp != null\">\n" +
            "        #{maxmp,jdbcType=BIGINT},\n" +
            "      </if>\n" +
            "      <if test=\"maxgjl != null\">\n" +
            "        #{maxgjl,jdbcType=BIGINT},\n" +
            "      </if>\n" +
            "      <if test=\"maxjueduigjl != null\">\n" +
            "        #{maxjueduigjl,jdbcType=BIGINT},\n" +
            "      </if>\n" +
            "      <if test=\"maxfyl != null\">\n" +
            "        #{maxfyl,jdbcType=BIGINT},\n" +
            "      </if>\n" +
            "      <if test=\"maxjueduifyl != null\">\n" +
            "        #{maxjueduifyl,jdbcType=BIGINT},\n" +
            "      </if>\n" +
            "      <if test=\"xiaoguoleixing != null\">\n" +
            "        #{xiaoguoleixing,jdbcType=INTEGER},\n" +
            "      </if>\n" +
            "      <if test=\"leixing != null\">\n" +
            "        #{leixing,jdbcType=INTEGER},\n" +
            "      </if>\n" +
            "      <if test=\"needhp != null\">\n" +
            "        #{needhp,jdbcType=BIGINT},\n" +
            "      </if>\n" +
            "      <if test=\"needmp != null\">\n" +
            "        #{needmp,jdbcType=BIGINT},\n" +
            "      </if>\n" +
            "      <if test=\"needleixing != null\">\n" +
            "        #{needleixing,jdbcType=INTEGER},\n" +
            "      </if>\n" +
            "    </trim></script>")
    @Options(useGeneratedKeys = true,keyProperty = "id",keyColumn = "id")
    int insertSelective(Jineng record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jineng
     *
     * @mbg.generated
     */
    Jineng selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jineng
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Jineng record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jineng
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Jineng record);
}