package com.example.mydemo.dao;

import com.example.mydemo.bean.Jinengaction;

public interface JinengactionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinengaction
     *
     * @mbg.generated
     */
    int insert(Jinengaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jinengaction
     *
     * @mbg.generated
     */
    int insertSelective(Jinengaction record);
}