package com.example.mydemo.dao;

import com.example.mydemo.bean.Juese;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Repository
public interface JueseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juese
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String jueseid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juese
     *
     * @mbg.generated
     */
    int insert(Juese record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juese
     *
     * @mbg.generated
     */
    int insertSelective(Juese record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juese
     *
     * @mbg.generated
     */
    Juese selectByPrimaryKey(String jueseid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juese
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Juese record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table juese
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Juese record);
}