package com.example.mydemo.dao;

import com.example.mydemo.bean.Zdactioninfo;

public interface ZdactioninfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zdactioninfo
     *
     * @mbg.generated
     */
    int insert(Zdactioninfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zdactioninfo
     *
     * @mbg.generated
     */
    int insertSelective(Zdactioninfo record);
}