package com.example.mydemo.dao;

import com.example.mydemo.bean.Zdactioninfo;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Options;
import org.springframework.stereotype.Repository;

@Repository
public interface ZdactioninfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zdactioninfo
     *
     * @mbg.generated
     */
    @Insert("insert into zdactioninfo (zdactionid, zdtype, onevalue, \n" +
            "      twovalue, threevalue, percentage, \n" +
            "      typeaction, typevalue)\n" +
            "    values (#{zdactionid,jdbcType=INTEGER}, #{zdtype,jdbcType=INTEGER}, #{onevalue,jdbcType=BIGINT}, \n" +
            "      #{twovalue,jdbcType=BIGINT}, #{threevalue,jdbcType=BIGINT}, #{percentage,jdbcType=INTEGER}, \n" +
            "      #{typeaction,jdbcType=INTEGER}, #{typevalue,jdbcType=VARCHAR})")
    int insert(Zdactioninfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zdactioninfo
     *
     * @mbg.generated
     */
    @Insert("<script>" +
            "insert into zdactioninfo\n" +
            "    <trim prefix=\"(\" suffix=\")\" suffixOverrides=\",\">\n" +
            "      <if test=\"zdactionid != null\">\n" +
            "        zdactionid,\n" +
            "      </if>\n" +
            "      <if test=\"zdtype != null\">\n" +
            "        zdtype,\n" +
            "      </if>\n" +
            "      <if test=\"onevalue != null\">\n" +
            "        onevalue,\n" +
            "      </if>\n" +
            "      <if test=\"twovalue != null\">\n" +
            "        twovalue,\n" +
            "      </if>\n" +
            "      <if test=\"threevalue != null\">\n" +
            "        threevalue,\n" +
            "      </if>\n" +
            "      <if test=\"percentage != null\">\n" +
            "        percentage,\n" +
            "      </if>\n" +
            "      <if test=\"typeaction != null\">\n" +
            "        typeaction,\n" +
            "      </if>\n" +
            "      <if test=\"typevalue != null\">\n" +
            "        typevalue,\n" +
            "      </if>\n" +
            "    </trim>\n" +
            "    <trim prefix=\"values (\" suffix=\")\" suffixOverrides=\",\">\n" +
            "      <if test=\"zdactionid != null\">\n" +
            "        #{zdactionid,jdbcType=INTEGER},\n" +
            "      </if>\n" +
            "      <if test=\"zdtype != null\">\n" +
            "        #{zdtype,jdbcType=INTEGER},\n" +
            "      </if>\n" +
            "      <if test=\"onevalue != null\">\n" +
            "        #{onevalue,jdbcType=BIGINT},\n" +
            "      </if>\n" +
            "      <if test=\"twovalue != null\">\n" +
            "        #{twovalue,jdbcType=BIGINT},\n" +
            "      </if>\n" +
            "      <if test=\"threevalue != null\">\n" +
            "        #{threevalue,jdbcType=BIGINT},\n" +
            "      </if>\n" +
            "      <if test=\"percentage != null\">\n" +
            "        #{percentage,jdbcType=INTEGER},\n" +
            "      </if>\n" +
            "      <if test=\"typeaction != null\">\n" +
            "        #{typeaction,jdbcType=INTEGER},\n" +
            "      </if>\n" +
            "      <if test=\"typevalue != null\">\n" +
            "        #{typevalue,jdbcType=VARCHAR},\n" +
            "      </if>\n" +
            "    </trim>" +
            "</script>")
    int insertSelective(Zdactioninfo record);
}