package com.example.mydemo.dao;

import com.example.mydemo.bean.Zdaction;

public interface ZdactionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zdaction
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zdaction
     *
     * @mbg.generated
     */
    int insert(Zdaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zdaction
     *
     * @mbg.generated
     */
    int insertSelective(Zdaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zdaction
     *
     * @mbg.generated
     */
    Zdaction selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zdaction
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Zdaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zdaction
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Zdaction record);
}