package com.example.mydemo.dao;

import com.example.mydemo.bean.Zdactioninfo;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Select;

import java.util.List;
import java.util.Set;

public interface ZdactioninfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zdactioninfo
     *
     * @mbg.generated
     */
    @Insert("insert into zdactioninfo (zdactionid, onevalue, twovalue, \n" +
            "      threevalue, percentage, typeaction, \n" +
            "      typevalue)\n" +
            "    values (#{zdactionid,jdbcType=INTEGER}, #{onevalue,jdbcType=BIGINT}, #{twovalue,jdbcType=BIGINT}, \n" +
            "      #{threevalue,jdbcType=BIGINT}, #{percentage,jdbcType=INTEGER}, #{typeaction,jdbcType=INTEGER}, \n" +
            "      #{typevalue,jdbcType=VARCHAR})")
    int insert(Zdactioninfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zdactioninfo
     *
     * @mbg.generated
     */
    @Insert("<script>" +
            "insert into zdactioninfo\n" +
            "    <trim prefix=\"(\" suffix=\")\" suffixOverrides=\",\">\n" +
            "      <if test=\"zdactionid != null\">\n" +
            "        zdactionid,\n" +
            "      </if>\n" +
            "      <if test=\"onevalue != null\">\n" +
            "        onevalue,\n" +
            "      </if>\n" +
            "      <if test=\"twovalue != null\">\n" +
            "        twovalue,\n" +
            "      </if>\n" +
            "      <if test=\"threevalue != null\">\n" +
            "        threevalue,\n" +
            "      </if>\n" +
            "      <if test=\"percentage != null\">\n" +
            "        percentage,\n" +
            "      </if>\n" +
            "      <if test=\"typeaction != null\">\n" +
            "        typeaction,\n" +
            "      </if>\n" +
            "      <if test=\"typevalue != null\">\n" +
            "        typevalue,\n" +
            "      </if>\n" +
            "    </trim>\n" +
            "    <trim prefix=\"values (\" suffix=\")\" suffixOverrides=\",\">\n" +
            "      <if test=\"zdactionid != null\">\n" +
            "        #{zdactionid,jdbcType=INTEGER},\n" +
            "      </if>\n" +
            "      <if test=\"onevalue != null\">\n" +
            "        #{onevalue,jdbcType=BIGINT},\n" +
            "      </if>\n" +
            "      <if test=\"twovalue != null\">\n" +
            "        #{twovalue,jdbcType=BIGINT},\n" +
            "      </if>\n" +
            "      <if test=\"threevalue != null\">\n" +
            "        #{threevalue,jdbcType=BIGINT},\n" +
            "      </if>\n" +
            "      <if test=\"percentage != null\">\n" +
            "        #{percentage,jdbcType=INTEGER},\n" +
            "      </if>\n" +
            "      <if test=\"typeaction != null\">\n" +
            "        #{typeaction,jdbcType=INTEGER},\n" +
            "      </if>\n" +
            "      <if test=\"typevalue != null\">\n" +
            "        #{typevalue,jdbcType=VARCHAR},\n" +
            "      </if>\n" +
            "    </trim>" +
            "</script>")
    int insertSelective(Zdactioninfo record);


    @Select("SELECT * from zdactioninfo where zdactionid in (#{zdactionid})")
    Set<Zdactioninfo> selectByZdationid(List<Integer> zdactionid);
}