package com.example.mydemo.bean;

public class Herodictionary {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column herodictionary.mod
     *
     * @mbg.generated
     */
    private String mod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column herodictionary.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column herodictionary.orderby
     *
     * @mbg.generated
     */
    private Integer orderby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column herodictionary.modfield
     *
     * @mbg.generated
     */
    private String modfield;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column herodictionary.usestatus
     *
     * @mbg.generated
     */
    private Boolean usestatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column herodictionary.dictvalue
     *
     * @mbg.generated
     */
    private String dictvalue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column herodictionary.mod
     *
     * @return the value of herodictionary.mod
     *
     * @mbg.generated
     */
    public String getMod() {
        return mod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column herodictionary.mod
     *
     * @param mod the value for herodictionary.mod
     *
     * @mbg.generated
     */
    public void setMod(String mod) {
        this.mod = mod == null ? null : mod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column herodictionary.name
     *
     * @return the value of herodictionary.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column herodictionary.name
     *
     * @param name the value for herodictionary.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column herodictionary.orderby
     *
     * @return the value of herodictionary.orderby
     *
     * @mbg.generated
     */
    public Integer getOrderby() {
        return orderby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column herodictionary.orderby
     *
     * @param orderby the value for herodictionary.orderby
     *
     * @mbg.generated
     */
    public void setOrderby(Integer orderby) {
        this.orderby = orderby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column herodictionary.modfield
     *
     * @return the value of herodictionary.modfield
     *
     * @mbg.generated
     */
    public String getModfield() {
        return modfield;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column herodictionary.modfield
     *
     * @param modfield the value for herodictionary.modfield
     *
     * @mbg.generated
     */
    public void setModfield(String modfield) {
        this.modfield = modfield == null ? null : modfield.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column herodictionary.usestatus
     *
     * @return the value of herodictionary.usestatus
     *
     * @mbg.generated
     */
    public Boolean getUsestatus() {
        return usestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column herodictionary.usestatus
     *
     * @param usestatus the value for herodictionary.usestatus
     *
     * @mbg.generated
     */
    public void setUsestatus(Boolean usestatus) {
        this.usestatus = usestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column herodictionary.dictvalue
     *
     * @return the value of herodictionary.dictvalue
     *
     * @mbg.generated
     */
    public String getDictvalue() {
        return dictvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column herodictionary.dictvalue
     *
     * @param dictvalue the value for herodictionary.dictvalue
     *
     * @mbg.generated
     */
    public void setDictvalue(String dictvalue) {
        this.dictvalue = dictvalue == null ? null : dictvalue.trim();
    }
}