package com.example.mydemo.bean;

import com.example.mydemo.unitl.MyUuid;

public class Jineng {

    public Jineng(String name) {
        this.name = name;
        this.needhp = MyUuid.getRandom(100)+4;
        this.needmp = MyUuid.getRandom(100)+4;
        this.level = (needhp+needmp)>=200?3:(needhp+needmp)>=100?2:1;
        this.zhongzu = 0;
        this.shuxing = 0;
        this.xiaoguoleixing = MyUuid.getRandomInt(3) - 1;
        this.hp = MyUuid.getRandom(100)+34;
        this.mp = MyUuid.getRandom(100)+34;
        this.gjl = MyUuid.getRandom(10)+4;
        this.jueduigjl = MyUuid.getRandom(3)+1;
        this.fyl = MyUuid.getRandom(10)+4;
        this.jueduifyl = MyUuid.getRandom(3)+1;
        this.maxhp = hp;
        this.maxmp = mp;
        this.maxgjl = gjl;
        this.maxjueduigjl = jueduigjl;
        this.maxfyl = fyl;
        this.maxjueduifyl = jueduifyl;
        this.leixing = 1;
        this.needleixing = 1;
        this.exp = 0;
    }

    public Jineng(String name, Integer level, Integer zhongzu, Integer shuxing, Long hp, Long mp, Long gjl, Long jueduigjl, Long fyl, Long jueduifyl,  Integer xiaoguoleixing, Integer leixing, Long needhp, Long needmp, Integer needleixing) {
        this.name = name;
        this.level = level;
        this.zhongzu = zhongzu;
        this.shuxing = shuxing;
        this.hp = hp;
        this.mp = mp;
        this.gjl = gjl;
        this.jueduigjl = jueduigjl;
        this.fyl = fyl;
        this.jueduifyl = jueduifyl;
        this.maxhp = hp;
        this.maxmp = mp;
        this.maxgjl = gjl;
        this.maxjueduigjl = jueduigjl;
        this.maxfyl = fyl;
        this.maxjueduifyl = jueduifyl;
        this.xiaoguoleixing = xiaoguoleixing;
        this.leixing = leixing;
        this.needhp = needhp;
        this.needmp = needmp;
        this.needleixing = needleixing;
        this.exp = 0;
    }

    public Jineng(String name, Integer level, Integer zhongzu, Integer shuxing, Long hp, Long mp, Long gjl, Long jueduigjl, Long fyl, Long jueduifyl,  Integer xiaoguoleixing, Integer leixing, Long needhp, Long needmp) {
        this.name = name;
        this.level = level;
        this.zhongzu = zhongzu;
        this.shuxing = shuxing;
        this.hp = hp;
        this.mp = mp;
        this.gjl = gjl;
        this.jueduigjl = jueduigjl;
        this.fyl = fyl;
        this.jueduifyl = jueduifyl;
        this.maxhp = hp;
        this.maxmp = mp;
        this.maxgjl = gjl;
        this.maxjueduigjl = jueduigjl;
        this.maxfyl = fyl;
        this.maxjueduifyl = jueduifyl;
        this.xiaoguoleixing = xiaoguoleixing;
        this.leixing = leixing;
        this.needhp = needhp;
        this.needmp = needmp;
        this.needleixing = 1;
        this.exp = 0;
    }


    public Jineng(String name, Integer level, Integer zhongzu, Integer shuxing, Long hp, Long mp, Long gjl, Long jueduigjl, Long fyl, Long jueduifyl,  Integer xiaoguoleixing, Integer leixing, Long needhp, Long needmp, Integer needleixing,Integer exp) {
        this.name = name;
        this.level = level;
        this.zhongzu = zhongzu;
        this.shuxing = shuxing;
        this.hp = hp;
        this.mp = mp;
        this.gjl = gjl;
        this.jueduigjl = jueduigjl;
        this.fyl = fyl;
        this.jueduifyl = jueduifyl;
        this.maxhp = hp;
        this.maxmp = mp;
        this.maxgjl = gjl;
        this.maxjueduigjl = jueduigjl;
        this.maxfyl = fyl;
        this.maxjueduifyl = jueduifyl;
        this.xiaoguoleixing = xiaoguoleixing;
        this.leixing = leixing;
        this.needhp = needhp;
        this.needmp = needmp;
        this.needleixing = needleixing;
        this.exp = exp;
    }

    private Integer exp;

    public Integer getExp() {
        return exp;
    }

    public void setExp(Integer exp) {
        this.exp = exp;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jineng.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jineng.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jineng.level
     *
     * @mbg.generated
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jineng.zhongzu
     *
     * @mbg.generated
     */
    private Integer zhongzu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jineng.shuxing
     *
     * @mbg.generated
     */
    private Integer shuxing;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jineng.hp
     *
     * @mbg.generated
     */
    private Long hp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jineng.mp
     *
     * @mbg.generated
     */
    private Long mp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jineng.gjl
     *
     * @mbg.generated
     */
    private Long gjl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jineng.jueduigjl
     *
     * @mbg.generated
     */
    private Long jueduigjl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jineng.fyl
     *
     * @mbg.generated
     */
    private Long fyl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jineng.jueduifyl
     *
     * @mbg.generated
     */
    private Long jueduifyl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jineng.maxhp
     *
     * @mbg.generated
     */
    private Long maxhp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jineng.maxmp
     *
     * @mbg.generated
     */
    private Long maxmp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jineng.maxgjl
     *
     * @mbg.generated
     */
    private Long maxgjl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jineng.maxjueduigjl
     *
     * @mbg.generated
     */
    private Long maxjueduigjl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jineng.maxfyl
     *
     * @mbg.generated
     */
    private Long maxfyl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jineng.maxjueduifyl
     *
     * @mbg.generated
     */
    private Long maxjueduifyl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jineng.xiaoguoleixing
     *
     * @mbg.generated
     */
    private Integer xiaoguoleixing;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jineng.leixing
     *
     * @mbg.generated
     */
    private Integer leixing;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jineng.needhp
     *
     * @mbg.generated
     */
    private Long needhp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jineng.needmp
     *
     * @mbg.generated
     */
    private Long needmp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jineng.needleixing
     *
     * @mbg.generated
     */
    private Integer needleixing;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jineng.id
     *
     * @return the value of jineng.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jineng.id
     *
     * @param id the value for jineng.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jineng.name
     *
     * @return the value of jineng.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jineng.name
     *
     * @param name the value for jineng.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jineng.level
     *
     * @return the value of jineng.level
     *
     * @mbg.generated
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jineng.level
     *
     * @param level the value for jineng.level
     *
     * @mbg.generated
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jineng.zhongzu
     *
     * @return the value of jineng.zhongzu
     *
     * @mbg.generated
     */
    public Integer getZhongzu() {
        return zhongzu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jineng.zhongzu
     *
     * @param zhongzu the value for jineng.zhongzu
     *
     * @mbg.generated
     */
    public void setZhongzu(Integer zhongzu) {
        this.zhongzu = zhongzu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jineng.shuxing
     *
     * @return the value of jineng.shuxing
     *
     * @mbg.generated
     */
    public Integer getShuxing() {
        return shuxing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jineng.shuxing
     *
     * @param shuxing the value for jineng.shuxing
     *
     * @mbg.generated
     */
    public void setShuxing(Integer shuxing) {
        this.shuxing = shuxing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jineng.hp
     *
     * @return the value of jineng.hp
     *
     * @mbg.generated
     */
    public Long getHp() {
        return hp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jineng.hp
     *
     * @param hp the value for jineng.hp
     *
     * @mbg.generated
     */
    public void setHp(Long hp) {
        this.hp = hp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jineng.mp
     *
     * @return the value of jineng.mp
     *
     * @mbg.generated
     */
    public Long getMp() {
        return mp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jineng.mp
     *
     * @param mp the value for jineng.mp
     *
     * @mbg.generated
     */
    public void setMp(Long mp) {
        this.mp = mp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jineng.gjl
     *
     * @return the value of jineng.gjl
     *
     * @mbg.generated
     */
    public Long getGjl() {
        return gjl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jineng.gjl
     *
     * @param gjl the value for jineng.gjl
     *
     * @mbg.generated
     */
    public void setGjl(Long gjl) {
        this.gjl = gjl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jineng.jueduigjl
     *
     * @return the value of jineng.jueduigjl
     *
     * @mbg.generated
     */
    public Long getJueduigjl() {
        return jueduigjl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jineng.jueduigjl
     *
     * @param jueduigjl the value for jineng.jueduigjl
     *
     * @mbg.generated
     */
    public void setJueduigjl(Long jueduigjl) {
        this.jueduigjl = jueduigjl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jineng.fyl
     *
     * @return the value of jineng.fyl
     *
     * @mbg.generated
     */
    public Long getFyl() {
        return fyl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jineng.fyl
     *
     * @param fyl the value for jineng.fyl
     *
     * @mbg.generated
     */
    public void setFyl(Long fyl) {
        this.fyl = fyl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jineng.jueduifyl
     *
     * @return the value of jineng.jueduifyl
     *
     * @mbg.generated
     */
    public Long getJueduifyl() {
        return jueduifyl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jineng.jueduifyl
     *
     * @param jueduifyl the value for jineng.jueduifyl
     *
     * @mbg.generated
     */
    public void setJueduifyl(Long jueduifyl) {
        this.jueduifyl = jueduifyl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jineng.maxhp
     *
     * @return the value of jineng.maxhp
     *
     * @mbg.generated
     */
    public Long getMaxhp() {
        return maxhp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jineng.maxhp
     *
     * @param maxhp the value for jineng.maxhp
     *
     * @mbg.generated
     */
    public void setMaxhp(Long maxhp) {
        this.maxhp = maxhp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jineng.maxmp
     *
     * @return the value of jineng.maxmp
     *
     * @mbg.generated
     */
    public Long getMaxmp() {
        return maxmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jineng.maxmp
     *
     * @param maxmp the value for jineng.maxmp
     *
     * @mbg.generated
     */
    public void setMaxmp(Long maxmp) {
        this.maxmp = maxmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jineng.maxgjl
     *
     * @return the value of jineng.maxgjl
     *
     * @mbg.generated
     */
    public Long getMaxgjl() {
        return maxgjl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jineng.maxgjl
     *
     * @param maxgjl the value for jineng.maxgjl
     *
     * @mbg.generated
     */
    public void setMaxgjl(Long maxgjl) {
        this.maxgjl = maxgjl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jineng.maxjueduigjl
     *
     * @return the value of jineng.maxjueduigjl
     *
     * @mbg.generated
     */
    public Long getMaxjueduigjl() {
        return maxjueduigjl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jineng.maxjueduigjl
     *
     * @param maxjueduigjl the value for jineng.maxjueduigjl
     *
     * @mbg.generated
     */
    public void setMaxjueduigjl(Long maxjueduigjl) {
        this.maxjueduigjl = maxjueduigjl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jineng.maxfyl
     *
     * @return the value of jineng.maxfyl
     *
     * @mbg.generated
     */
    public Long getMaxfyl() {
        return maxfyl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jineng.maxfyl
     *
     * @param maxfyl the value for jineng.maxfyl
     *
     * @mbg.generated
     */
    public void setMaxfyl(Long maxfyl) {
        this.maxfyl = maxfyl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jineng.maxjueduifyl
     *
     * @return the value of jineng.maxjueduifyl
     *
     * @mbg.generated
     */
    public Long getMaxjueduifyl() {
        return maxjueduifyl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jineng.maxjueduifyl
     *
     * @param maxjueduifyl the value for jineng.maxjueduifyl
     *
     * @mbg.generated
     */
    public void setMaxjueduifyl(Long maxjueduifyl) {
        this.maxjueduifyl = maxjueduifyl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jineng.xiaoguoleixing
     *
     * @return the value of jineng.xiaoguoleixing
     *
     * @mbg.generated
     */
    public Integer getXiaoguoleixing() {
        return xiaoguoleixing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jineng.xiaoguoleixing
     *
     * @param xiaoguoleixing the value for jineng.xiaoguoleixing
     *
     * @mbg.generated
     */
    public void setXiaoguoleixing(Integer xiaoguoleixing) {
        this.xiaoguoleixing = xiaoguoleixing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jineng.leixing
     *
     * @return the value of jineng.leixing
     *
     * @mbg.generated
     */
    public Integer getLeixing() {
        return leixing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jineng.leixing
     *
     * @param leixing the value for jineng.leixing
     *
     * @mbg.generated
     */
    public void setLeixing(Integer leixing) {
        this.leixing = leixing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jineng.needhp
     *
     * @return the value of jineng.needhp
     *
     * @mbg.generated
     */
    public Long getNeedhp() {
        return needhp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jineng.needhp
     *
     * @param needhp the value for jineng.needhp
     *
     * @mbg.generated
     */
    public void setNeedhp(Long needhp) {
        this.needhp = needhp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jineng.needmp
     *
     * @return the value of jineng.needmp
     *
     * @mbg.generated
     */
    public Long getNeedmp() {
        return needmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jineng.needmp
     *
     * @param needmp the value for jineng.needmp
     *
     * @mbg.generated
     */
    public void setNeedmp(Long needmp) {
        this.needmp = needmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jineng.needleixing
     *
     * @return the value of jineng.needleixing
     *
     * @mbg.generated
     */
    public Integer getNeedleixing() {
        return needleixing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jineng.needleixing
     *
     * @param needleixing the value for jineng.needleixing
     *
     * @mbg.generated
     */
    public void setNeedleixing(Integer needleixing) {
        this.needleixing = needleixing;
    }
}