package com.example.mydemo.bean;

import com.example.mydemo.unitl.MyUuid;

import java.util.HashSet;
import java.util.Random;
import java.util.Set;
import java.util.UUID;

public class Juese {
    public Juese() {
        super();
    }

    public Juese(String name, Integer zhongzu, Long hp, Long mp, Long gjl, Long jueduigjl, Long fyl, Long jueduifyl, Integer level, Integer pinji) {
        this.name = name;
        this.zhongzu = zhongzu;
        this.hp = hp;
        this.mp = mp;
        this.gjl = gjl;
        this.jueduigjl = jueduigjl;
        this.fyl = fyl;
        this.jueduifyl = jueduifyl;
        this.level = level;
        this.pinji = pinji;
        this.jueseid = UUID.randomUUID().toString();
        this.maxhp = hp;
        this.maxmp = mp;
        this.maxfyl =fyl;
        this.maxgjl =gjl;
        this.maxjueduifyl =jueduifyl;
        this.maxjueduigjl =jueduigjl;
    }

    public Juese(String name) {
        this.name = name;
        this.zhongzu = MyUuid.getRandomInt(2);
        this.hp = MyUuid.getRandom(128)+15;
        this.mp = MyUuid.getRandom(64)+9;
        this.gjl = MyUuid.getRandom(25)+4;
        this.jueduigjl = MyUuid.getRandom(5);
        this.fyl = MyUuid.getRandom(25)+4;
        this.jueduifyl = MyUuid.getRandom(5);
        this.level = 1;
        this.pinji = 1;
        this.jueseid = UUID.randomUUID().toString();
        this.maxhp = this.hp;
        this.maxmp = this.mp;
        this.maxfyl = this.fyl;
        this.maxgjl = this.gjl;
        this.maxjueduifyl = this.jueduifyl;
        this.maxjueduigjl = this.jueduigjl;
    }


    public Set<Juesejineng> getJuesejinengs() {
        return juesejinengs;
    }

    public void setJuesejinengs(Set<Juesejineng> juesejinengs) {
        this.juesejinengs = juesejinengs;
    }

    //角色技能清单
    private Set<Juesejineng> juesejinengs = new HashSet<>();
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juese.jueseID
     *
     * @mbg.generated
     */
    private String jueseid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juese.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juese.zhongzu
     *
     * @mbg.generated
     */
    private Integer zhongzu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juese.hp
     *
     * @mbg.generated
     */
    private Long hp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juese.mp
     *
     * @mbg.generated
     */
    private Long mp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juese.gjl
     *
     * @mbg.generated
     */
    private Long gjl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juese.jueduigjl
     *
     * @mbg.generated
     */
    private Long jueduigjl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juese.fyl
     *
     * @mbg.generated
     */
    private Long fyl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juese.jueduifyl
     *
     * @mbg.generated
     */
    private Long jueduifyl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juese.level
     *
     * @mbg.generated
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juese.pinji
     *
     * @mbg.generated
     */
    private Integer pinji;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juese.maxhp
     *
     * @mbg.generated
     */
    private Long maxhp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juese.maxmp
     *
     * @mbg.generated
     */
    private Long maxmp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juese.maxgjl
     *
     * @mbg.generated
     */
    private Long maxgjl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juese.maxfyl
     *
     * @mbg.generated
     */
    private Long maxfyl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juese.maxjueduigjl
     *
     * @mbg.generated
     */
    private Long maxjueduigjl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column juese.maxjueduifyl
     *
     * @mbg.generated
     */
    private Long maxjueduifyl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juese.jueseID
     *
     * @return the value of juese.jueseID
     *
     * @mbg.generated
     */
    public String getJueseid() {
        return jueseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juese.jueseID
     *
     * @param jueseid the value for juese.jueseID
     *
     * @mbg.generated
     */
    public void setJueseid(String jueseid) {
        this.jueseid = jueseid == null ? null : jueseid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juese.name
     *
     * @return the value of juese.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juese.name
     *
     * @param name the value for juese.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juese.zhongzu
     *
     * @return the value of juese.zhongzu
     *
     * @mbg.generated
     */
    public Integer getZhongzu() {
        return zhongzu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juese.zhongzu
     *
     * @param zhongzu the value for juese.zhongzu
     *
     * @mbg.generated
     */
    public void setZhongzu(Integer zhongzu) {
        this.zhongzu = zhongzu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juese.hp
     *
     * @return the value of juese.hp
     *
     * @mbg.generated
     */
    public Long getHp() {
        return hp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juese.hp
     *
     * @param hp the value for juese.hp
     *
     * @mbg.generated
     */
    public void setHp(Long hp) {
        this.hp = hp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juese.mp
     *
     * @return the value of juese.mp
     *
     * @mbg.generated
     */
    public Long getMp() {
        return mp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juese.mp
     *
     * @param mp the value for juese.mp
     *
     * @mbg.generated
     */
    public void setMp(Long mp) {
        this.mp = mp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juese.gjl
     *
     * @return the value of juese.gjl
     *
     * @mbg.generated
     */
    public Long getGjl() {
        return gjl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juese.gjl
     *
     * @param gjl the value for juese.gjl
     *
     * @mbg.generated
     */
    public void setGjl(Long gjl) {
        this.gjl = gjl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juese.jueduigjl
     *
     * @return the value of juese.jueduigjl
     *
     * @mbg.generated
     */
    public Long getJueduigjl() {
        return jueduigjl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juese.jueduigjl
     *
     * @param jueduigjl the value for juese.jueduigjl
     *
     * @mbg.generated
     */
    public void setJueduigjl(Long jueduigjl) {
        this.jueduigjl = jueduigjl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juese.fyl
     *
     * @return the value of juese.fyl
     *
     * @mbg.generated
     */
    public Long getFyl() {
        return fyl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juese.fyl
     *
     * @param fyl the value for juese.fyl
     *
     * @mbg.generated
     */
    public void setFyl(Long fyl) {
        this.fyl = fyl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juese.jueduifyl
     *
     * @return the value of juese.jueduifyl
     *
     * @mbg.generated
     */
    public Long getJueduifyl() {
        return jueduifyl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juese.jueduifyl
     *
     * @param jueduifyl the value for juese.jueduifyl
     *
     * @mbg.generated
     */
    public void setJueduifyl(Long jueduifyl) {
        this.jueduifyl = jueduifyl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juese.level
     *
     * @return the value of juese.level
     *
     * @mbg.generated
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juese.level
     *
     * @param level the value for juese.level
     *
     * @mbg.generated
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juese.pinji
     *
     * @return the value of juese.pinji
     *
     * @mbg.generated
     */
    public Integer getPinji() {
        return pinji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juese.pinji
     *
     * @param pinji the value for juese.pinji
     *
     * @mbg.generated
     */
    public void setPinji(Integer pinji) {
        this.pinji = pinji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juese.maxhp
     *
     * @return the value of juese.maxhp
     *
     * @mbg.generated
     */
    public Long getMaxhp() {
        return maxhp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juese.maxhp
     *
     * @param maxhp the value for juese.maxhp
     *
     * @mbg.generated
     */
    public void setMaxhp(Long maxhp) {
        this.maxhp = maxhp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juese.maxmp
     *
     * @return the value of juese.maxmp
     *
     * @mbg.generated
     */
    public Long getMaxmp() {
        return maxmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juese.maxmp
     *
     * @param maxmp the value for juese.maxmp
     *
     * @mbg.generated
     */
    public void setMaxmp(Long maxmp) {
        this.maxmp = maxmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juese.maxgjl
     *
     * @return the value of juese.maxgjl
     *
     * @mbg.generated
     */
    public Long getMaxgjl() {
        return maxgjl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juese.maxgjl
     *
     * @param maxgjl the value for juese.maxgjl
     *
     * @mbg.generated
     */
    public void setMaxgjl(Long maxgjl) {
        this.maxgjl = maxgjl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juese.maxfyl
     *
     * @return the value of juese.maxfyl
     *
     * @mbg.generated
     */
    public Long getMaxfyl() {
        return maxfyl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juese.maxfyl
     *
     * @param maxfyl the value for juese.maxfyl
     *
     * @mbg.generated
     */
    public void setMaxfyl(Long maxfyl) {
        this.maxfyl = maxfyl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juese.maxjueduigjl
     *
     * @return the value of juese.maxjueduigjl
     *
     * @mbg.generated
     */
    public Long getMaxjueduigjl() {
        return maxjueduigjl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juese.maxjueduigjl
     *
     * @param maxjueduigjl the value for juese.maxjueduigjl
     *
     * @mbg.generated
     */
    public void setMaxjueduigjl(Long maxjueduigjl) {
        this.maxjueduigjl = maxjueduigjl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column juese.maxjueduifyl
     *
     * @return the value of juese.maxjueduifyl
     *
     * @mbg.generated
     */
    public Long getMaxjueduifyl() {
        return maxjueduifyl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column juese.maxjueduifyl
     *
     * @param maxjueduifyl the value for juese.maxjueduifyl
     *
     * @mbg.generated
     */
    public void setMaxjueduifyl(Long maxjueduifyl) {
        this.maxjueduifyl = maxjueduifyl;
    }
}