package com.example.mydemo.bean;

import java.util.Date;

public class Room {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.roomid
     *
     * @mbg.generated
     */
    private String roomid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.roomno
     *
     * @mbg.generated
     */
    private String roomno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.roomheight
     *
     * @mbg.generated
     */
    private Double roomheight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.roomwidth
     *
     * @mbg.generated
     */
    private Double roomwidth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.roomlength
     *
     * @mbg.generated
     */
    private Double roomlength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.infostatus
     *
     * @mbg.generated
     */
    private Boolean infostatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.createtime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.updatetime
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.roomid
     *
     * @return the value of room.roomid
     *
     * @mbg.generated
     */
    public String getRoomid() {
        return roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.roomid
     *
     * @param roomid the value for room.roomid
     *
     * @mbg.generated
     */
    public void setRoomid(String roomid) {
        this.roomid = roomid == null ? null : roomid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.roomno
     *
     * @return the value of room.roomno
     *
     * @mbg.generated
     */
    public String getRoomno() {
        return roomno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.roomno
     *
     * @param roomno the value for room.roomno
     *
     * @mbg.generated
     */
    public void setRoomno(String roomno) {
        this.roomno = roomno == null ? null : roomno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.roomheight
     *
     * @return the value of room.roomheight
     *
     * @mbg.generated
     */
    public Double getRoomheight() {
        return roomheight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.roomheight
     *
     * @param roomheight the value for room.roomheight
     *
     * @mbg.generated
     */
    public void setRoomheight(Double roomheight) {
        this.roomheight = roomheight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.roomwidth
     *
     * @return the value of room.roomwidth
     *
     * @mbg.generated
     */
    public Double getRoomwidth() {
        return roomwidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.roomwidth
     *
     * @param roomwidth the value for room.roomwidth
     *
     * @mbg.generated
     */
    public void setRoomwidth(Double roomwidth) {
        this.roomwidth = roomwidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.roomlength
     *
     * @return the value of room.roomlength
     *
     * @mbg.generated
     */
    public Double getRoomlength() {
        return roomlength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.roomlength
     *
     * @param roomlength the value for room.roomlength
     *
     * @mbg.generated
     */
    public void setRoomlength(Double roomlength) {
        this.roomlength = roomlength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.infostatus
     *
     * @return the value of room.infostatus
     *
     * @mbg.generated
     */
    public Boolean getInfostatus() {
        return infostatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.infostatus
     *
     * @param infostatus the value for room.infostatus
     *
     * @mbg.generated
     */
    public void setInfostatus(Boolean infostatus) {
        this.infostatus = infostatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.createtime
     *
     * @return the value of room.createtime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.createtime
     *
     * @param createtime the value for room.createtime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.updatetime
     *
     * @return the value of room.updatetime
     *
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.updatetime
     *
     * @param updatetime the value for room.updatetime
     *
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}