package com.example.mydemo.bean;

public class Zdactioninfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zdactioninfo.zdactionid
     *
     * @mbg.generated
     */
    private Integer zdactionid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zdactioninfo.zdtype
     *
     * @mbg.generated
     */
    private Integer zdtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zdactioninfo.onevalue
     *
     * @mbg.generated
     */
    private Long onevalue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zdactioninfo.twovalue
     *
     * @mbg.generated
     */
    private Long twovalue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zdactioninfo.threevalue
     *
     * @mbg.generated
     */
    private Long threevalue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zdactioninfo.percentage
     *
     * @mbg.generated
     */
    private Integer percentage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zdactioninfo.typeaction
     *
     * @mbg.generated
     */
    private Integer typeaction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zdactioninfo.typevalue
     *
     * @mbg.generated
     */
    private String typevalue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zdactioninfo.zdactionid
     *
     * @return the value of zdactioninfo.zdactionid
     *
     * @mbg.generated
     */
    public Integer getZdactionid() {
        return zdactionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zdactioninfo.zdactionid
     *
     * @param zdactionid the value for zdactioninfo.zdactionid
     *
     * @mbg.generated
     */
    public void setZdactionid(Integer zdactionid) {
        this.zdactionid = zdactionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zdactioninfo.zdtype
     *
     * @return the value of zdactioninfo.zdtype
     *
     * @mbg.generated
     */
    public Integer getZdtype() {
        return zdtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zdactioninfo.zdtype
     *
     * @param zdtype the value for zdactioninfo.zdtype
     *
     * @mbg.generated
     */
    public void setZdtype(Integer zdtype) {
        this.zdtype = zdtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zdactioninfo.onevalue
     *
     * @return the value of zdactioninfo.onevalue
     *
     * @mbg.generated
     */
    public Long getOnevalue() {
        return onevalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zdactioninfo.onevalue
     *
     * @param onevalue the value for zdactioninfo.onevalue
     *
     * @mbg.generated
     */
    public void setOnevalue(Long onevalue) {
        this.onevalue = onevalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zdactioninfo.twovalue
     *
     * @return the value of zdactioninfo.twovalue
     *
     * @mbg.generated
     */
    public Long getTwovalue() {
        return twovalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zdactioninfo.twovalue
     *
     * @param twovalue the value for zdactioninfo.twovalue
     *
     * @mbg.generated
     */
    public void setTwovalue(Long twovalue) {
        this.twovalue = twovalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zdactioninfo.threevalue
     *
     * @return the value of zdactioninfo.threevalue
     *
     * @mbg.generated
     */
    public Long getThreevalue() {
        return threevalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zdactioninfo.threevalue
     *
     * @param threevalue the value for zdactioninfo.threevalue
     *
     * @mbg.generated
     */
    public void setThreevalue(Long threevalue) {
        this.threevalue = threevalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zdactioninfo.percentage
     *
     * @return the value of zdactioninfo.percentage
     *
     * @mbg.generated
     */
    public Integer getPercentage() {
        return percentage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zdactioninfo.percentage
     *
     * @param percentage the value for zdactioninfo.percentage
     *
     * @mbg.generated
     */
    public void setPercentage(Integer percentage) {
        this.percentage = percentage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zdactioninfo.typeaction
     *
     * @return the value of zdactioninfo.typeaction
     *
     * @mbg.generated
     */
    public Integer getTypeaction() {
        return typeaction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zdactioninfo.typeaction
     *
     * @param typeaction the value for zdactioninfo.typeaction
     *
     * @mbg.generated
     */
    public void setTypeaction(Integer typeaction) {
        this.typeaction = typeaction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zdactioninfo.typevalue
     *
     * @return the value of zdactioninfo.typevalue
     *
     * @mbg.generated
     */
    public String getTypevalue() {
        return typevalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zdactioninfo.typevalue
     *
     * @param typevalue the value for zdactioninfo.typevalue
     *
     * @mbg.generated
     */
    public void setTypevalue(String typevalue) {
        this.typevalue = typevalue == null ? null : typevalue.trim();
    }
}